### ISSUE TITLE
Create Sprite for Aloe Vera Plant

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#51]
Please see CONTRIBUTING.md first.

**Comment by inwardgarden** [comment]
I toyed around trying to create this. What do you think about these/this direction? I wasn't sure if this may violate the "no strong outlines" guideline and/or proper angle for world sprites. Still thinking about refining the leaves/lines a bit. 

Regular: ![aloe_vera](https://user-images.githubusercontent.com/6904118/31261026-dc021e28-aa1f-11e7-9f95-7c890781e09f.png) Serrated/spiky version: ![aloe_vera_spiky](https://user-images.githubusercontent.com/6904118/31261027-dc05e7b0-aa1f-11e7-8c25-73d20c3f0cf6.png)

**Comment by doficia** [comment]
Hi @bscottx! Well, drawing Aloe Vera is hard. I failed several times trying to get it right. :smiley: Angle is fine! You could try placing the highlight only on one side, giving it a backlit effect maybe, and less of a pillow shading. But it does not look bad at all, if you don't feel like working more on it, you can give a PR, I'll accept it. :smiley: Cheers!

**Comment by inwardgarden** [comment]
Not a bad idea. Worked on it a bit more. If you have any other ideas for refining, feel free to ask, otherwise I'll submit a PR in a little while.

![aloe_vera_sidelit](https://user-images.githubusercontent.com/6904118/31303930-97c27f44-aae4-11e7-8bf7-69ff28b24e4d.png)

Black BG for preview: ![aloe_vera_sidelit_bl_preview](https://user-images.githubusercontent.com/6904118/31303954-00e81be6-aae5-11e7-8503-06492efea994.png)

**Comment by doficia** [comment]
LGTM @bscottx. You can submit a PR. :smiley:
